name: food_delivery
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0  # Update to a version compatible with intl ^0.17.0
  cloud_firestore: ^4.15.10
  firebase_storage: ^11.6.11
  firebase_messaging: ^14.7.21
  # Add more Firebase packages as needed

  # Other dependencies
  shake: ^2.2.0
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.7
  google_maps_flutter: ^2.3.1
  custom_map_markers: ^0.0.2+1
  http: ^1.1.0
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.1.2
  intl: ^0.19.0  # Downgrade to the version required by firebase_auth
  flutter_timezone: ^1.0.6
  get_it: ^7.6.0
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.0.9
  sensors: ^2.0.3
  dio: ^5.4.2+1
  webview_flutter: ^4.7.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - asset/recipies.json/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/font/Metropolis-Regular.otf
        - asset: assets/font/Metropolis-Medium.otf
          weight: 500
        - asset: assets/font/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/font/Metropolis-Bold.otf
          weight: 700
        - asset: assets/font/Metropolis-ExtraBold.otf
          weight: 800
